apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: oidc-oauth2-workshop:latest
        name: oidc-oauth2-workshop
        imagePullPolicy: Never
        command:
        - "python"
        - "/usr/src/protected-api/app/protected-api.py"
        workingDir: /usr/src/protected-api/app
        env:
        - name: FLASK_APP
          value: api-auth-server.py
        - name: FLASK_ENV
          value: development
        - name: OIDC_JWKS_URL
          value: http://$IDP_HOSTNAME/.well-known/jwks.json
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5002
  selector:
    app: api
